CATALOGUES.FILE: CATALOGUES.table 
GEN_GUID.SRVPGM: GEN_GUID.sqludf 
MAIN_LOOP.FILE: MAIN_LOOP.view MAIN.FILE MAIN_LOOP.FILE
MAIN.FILE: MAIN.table 
LINES_VIEW.FILE: LINES_VW.view LINES.FILE
LINES.FILE: LINES.table 

