CATALOGUES.FILE: CATALOGUES.table 
GEN_GUID.SRVPGM: GEN_GUID.sqludf 
MAIN.FILE: MAIN.table
LINES_VIEW.FILE: LINES_VIEW.view LINES.FILE MAIN.FILE
LINES.FILE: LINES.table 
MAIN_LOOP.FILE: MAIN_LOOP.view MAIN.FILE

